"""O que as regras das empresas precisam do banco."""

from collections.abc import Mapping
from typing import Protocol

from .limites import Limites, Uso


class RepositorioDeEmpresas(Protocol):
    def existe(self, empresa_id: int) -> bool: ...
    def modulos(self, empresa_id: int) -> tuple[str | None, str | None] | None: ...   # (liberados, do plano)
    def limites(self, empresa_id: int) -> Limites: ...
    def uso(self, empresa_id: int) -> Uso: ...
    def codigo_em_uso(self, codigo: str, exceto_id: int | None = None) -> bool: ...

    def salvar_configuracoes(self, empresa_id: int, nome: str, codigo: str, emails: str, webhook: str,
                             cadastro: Mapping[str, str]) -> None:
        """Levanta CodigoEmUso se outra loja gravou o mesmo código ao mesmo tempo."""
        ...

    def remover_logo(self, empresa_id: int) -> None: ...
    def renomear(self, empresa_id: int, nome: str) -> None: ...
    def criar(self, nome: str, codigo: str, email_cobranca: str) -> int: ...
    def apagar(self, empresa_id: int) -> None: ...
