"""O que a cobrança precisa do Asaas (a implementação HTTP fica na infraestrutura)."""

from typing import Any, Protocol


class GatewayDeCobranca(Protocol):
    """Erros do Asaas (recusa, fora do ar) chegam como ErroNoGateway."""

    def criar_cliente(self, nome: str, documento: str, email: str, referencia: str) -> dict[str, Any]: ...
    def criar_assinatura(self, cliente_id: str, valor_centavos: int, primeiro_vencimento: str, descricao: str,
                         referencia: str) -> dict[str, Any]: ...
    def atualizar_assinatura(self, assinatura_id: str, valor_centavos: int, descricao: str) -> dict[str, Any]: ...
    def cancelar_assinatura(self, assinatura_id: str) -> dict[str, Any]: ...
    def faturas_da_assinatura(self, assinatura_id: str) -> list[dict[str, Any]]: ...
    def buscar_fatura(self, fatura_id: str) -> dict[str, Any]: ...
