"""O que a cobrança precisa do banco. Cobrança é da plataforma: o repositório enxerga todas as empresas."""

from datetime import date, datetime
from typing import Protocol

from .entidades import DadosDoPlano, EmpresaCobrada, Fatura, Plano


class RepositorioDeCobranca(Protocol):
    def empresa(self, empresa_id: int) -> EmpresaCobrada | None: ...
    def empresa_da_assinatura(self, assinatura_id: str) -> EmpresaCobrada | None: ...
    def empresas_com_assinatura(self) -> list[EmpresaCobrada]: ...
    def empresas_com_cobranca_automatica(self) -> list[int]: ...

    def plano(self, plano_id: int) -> Plano | None: ...
    def plano_com_nome(self, nome: str) -> bool: ...
    def inserir_plano(self, dados: DadosDoPlano) -> int: ...
    def atualizar_plano(self, plano_id: int, dados: DadosDoPlano) -> None: ...  # e os limites das empresas do plano

    def gravar_dados_de_cobranca(self, empresa_id: int, plano: Plano | None, documento: str, email: str,
                                 automatica: bool) -> None: ...
    def gravar_cliente_no_gateway(self, empresa_id: int, cliente_id: str) -> None: ...
    def gravar_assinatura(self, empresa_id: int, assinatura_id: str | None, automatica: bool) -> None: ...
    def gravar_contato(self, empresa_id: int, documento: str, email: str) -> None: ...
    def gravar_plano_da_empresa(self, empresa_id: int, plano: Plano) -> None: ...  # com os limites; cobrança automática
    def tirar_plano(self, empresa_id: int) -> None: ...  # sem plano, sem assinatura, sem cobrança automática
    def suspender_por_inadimplencia(self, empresa_id: int) -> None: ...
    def reativar(self, empresa_id: int) -> None: ...

    def gravar_fatura(self, empresa_id: int, fatura: Fatura, agora: datetime) -> None: ...
    def tem_fatura_vencida_antes_de(self, empresa_id: int, dia: date) -> bool: ...
    def faturas_em_aberto(self, empresa_id: int) -> list[str]: ...
    def cancelar_faturas(self, asaas_ids: list[str]) -> None: ...

    def evento_processado(self, evento_id: str) -> bool: ...
    def marcar_evento(self, evento_id: str, agora: datetime) -> None: ...
