"""O que as propagandas precisam do banco (a implementação fica na infraestrutura)."""

from collections.abc import Iterable
from contextlib import AbstractContextManager
from typing import Protocol

from .exibicao import Exibicao
from .propaganda import Destinos, Programacao, Propaganda


class RepositorioDePropagandas(Protocol):
    """Sempre restrito a uma loja."""

    def transacao(self) -> AbstractContextManager[None]: ...

    def listar(self) -> list[Propaganda]: ...          # na ordem de exibição, com os destinos
    def buscar(self, propaganda_id: int) -> Propaganda | None: ...
    def telas_da_loja(self) -> set[int]: ...
    def grupos_da_loja(self) -> set[int]: ...

    def inserir(self, nome: str, arquivo: str, tipo: str, tamanho: int, duracao: int, para_todas: bool) -> int: ...
    def gravar_programacao(self, propaganda_id: int, programacao: Programacao) -> None: ...
    def gravar_destinos(self, propaganda_id: int, destinos: Destinos) -> None: ...
    def gravar_ordem(self, ids: list[int]) -> None: ...
    def definir(self, ids: Iterable[int], campo: str, valor: object) -> None: ...  # ativo, duracao, letreiro, para_todas
    def excluir(self, propaganda_id: int) -> None: ...

    def config(self, chave: str) -> str | None: ...
    def gravar_config(self, chave: str, valor: str) -> None: ...

    def nomes(self) -> dict[int, str]: ...
    def gravar_exibicoes(self, tela_id: int, exibicoes: list[tuple[Exibicao, str]]) -> int: ...
