"""O que o painel (propagandas e telas) precisa do banco (a implementação fica na infraestrutura)."""

from collections.abc import Iterable
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from .exibicao import Exibicao
from .propaganda import Destinos, Programacao, Propaganda
from .telas import PedidoDeConexao, Tela


class RepositorioDePropagandas(Protocol):
    """Sempre restrito a uma loja."""

    def transacao(self) -> AbstractContextManager[None]: ...

    def listar(self) -> list[Propaganda]: ...          # na ordem de exibição, com os destinos
    def buscar(self, propaganda_id: int) -> Propaganda | None: ...
    def telas_da_loja(self) -> set[int]: ...
    def grupos_da_loja(self) -> set[int]: ...

    def inserir(self, nome: str, arquivo: str, tipo: str, tamanho: int, duracao: int, para_todas: bool) -> int: ...
    def gravar_programacao(self, propaganda_id: int, programacao: Programacao) -> None: ...
    def gravar_destinos(self, propaganda_id: int, destinos: Destinos) -> None: ...
    def gravar_ordem(self, ids: list[int]) -> None: ...
    def definir(self, ids: Iterable[int], campo: str, valor: object) -> None: ...  # ativo, duracao, letreiro, para_todas
    def excluir(self, propaganda_id: int) -> None: ...

    def config(self, chave: str) -> str | None: ...
    def gravar_config(self, chave: str, valor: str) -> None: ...

    def nomes(self) -> dict[int, str]: ...
    def gravar_exibicoes(self, tela_id: int, exibicoes: list[tuple[Exibicao, str]]) -> int: ...


class RepositorioDeTelas(Protocol):
    """Cadastro das telas e grupos de uma loja (o lado de quem administra)."""

    def telas(self) -> list[Tela]: ...
    def tela(self, tela_id: int) -> Tela | None: ...
    def endereco_em_uso(self, codigo: str) -> bool: ...
    def inserir_tela(self, nome: str, codigo: str, grupo_id: int | None) -> int: ...
    def atualizar_tela(self, tela_id: int, nome: str, grupo_id: int | None, letreiro: str | None) -> None: ...
    def trocar_endereco(self, tela_id: int, codigo: str) -> None: ...
    def desligar_aparelho(self, tela_id: int) -> None: ...
    def excluir_tela(self, tela_id: int) -> None: ...

    def grupo(self, grupo_id: int) -> str | None: ...
    def grupo_com_nome(self, nome: str) -> bool: ...
    def inserir_grupo(self, nome: str) -> int: ...
    def excluir_grupo(self, grupo_id: int) -> None: ...

    def pedido(self, codigo: str) -> PedidoDeConexao | None: ...
    def ligar_aparelho(self, tela_id: int, pedido: PedidoDeConexao, agora: datetime) -> None: ...


class RepositorioDeConexoes(Protocol):
    """O lado da TV: ela ainda não sabe de que loja é, só tem o endereço ou o crachá."""

    def tela_por_endereco(self, codigo: str) -> Tela | None: ...
    def tela(self, tela_id: int) -> Tela | None: ...
    def ligar_primeiro_aparelho(self, tela_id: int, cracha_hash: str, agora: datetime) -> bool: ...
    def apagar_pedidos_antigos(self, antes_de: datetime) -> None: ...
    def pedidos_abertos(self) -> int: ...
    def codigo_de_pedido_em_uso(self, codigo: str) -> bool: ...
    def inserir_pedido(self, codigo: str, segredo_hash: str, agora: datetime) -> None: ...
    def pedido_pelo_segredo(self, segredo_hash: str) -> PedidoDeConexao | None: ...
    def apagar_pedido(self, pedido_id: int) -> None: ...
    def registrar_contato(self, tela_id: int, agora: datetime, ip: str, navegador: str,
                          exibindo: str | None, mudar_exibindo: bool) -> None: ...
    def marcar_fechada(self, tela_id: int, agora: datetime) -> None: ...
