"""O que o cardápio precisa do banco (sempre de uma loja). Nome ou código repetido vira CategoriaRepetida/CodigoRepetido."""

from typing import Protocol

from .entidades import Categoria, DadosDoProduto, Produto


class RepositorioDeCardapio(Protocol):
    def categorias(self) -> list[Categoria]: ...          # na ordem do cardápio
    def categoria(self, categoria_id: int) -> Categoria | None: ...
    def inserir_categoria(self, nome: str) -> int: ...    # no fim da lista
    def renomear_categoria(self, categoria_id: int, nome: str) -> None: ...
    def gravar_ordem_das_categorias(self, ids: list[int]) -> None: ...
    def excluir_categoria(self, categoria_id: int) -> None: ...   # os produtos ficam sem categoria

    def produtos(self, so_ativos: bool) -> list[Produto]: ...      # na ordem do cardápio
    def produto(self, produto_id: int) -> Produto | None: ...
    def inserir_produto(self, dados: DadosDoProduto) -> int: ...
    def atualizar_produto(self, produto_id: int, dados: DadosDoProduto) -> None: ...
    def definir_ativo(self, produto_id: int, ativo: bool) -> None: ...
    def excluir_produto(self, produto_id: int) -> None: ...
