"""O que as permissões precisam do banco (a implementação fica na infraestrutura)."""

from collections.abc import Iterable
from contextlib import AbstractContextManager
from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from .liberacoes import Liberacao


@dataclass(frozen=True)
class Cadastro:
    """Um funcionário da loja, como está gravado (os módulos dele saem do papel e da loja)."""

    id: int
    nome: str
    papel: str
    plataforma: bool = False
    fecha_conta: bool = False


class RepositorioDePermissoes(Protocol):
    """Sempre restrito a uma loja: nada de outra loja aparece nem é alterado."""

    def transacao(self) -> AbstractContextManager[None]: ...

    # tabela de permissões
    def niveis_configurados(self) -> dict[tuple[str, str], int]: ...
    def gravar_niveis(self, niveis: dict[tuple[str, str], int]) -> None: ...
    def cadastro(self, usuario_id: int) -> Cadastro | None: ...

    # códigos e liberações
    def apagar_antigas(self, antes_de: datetime) -> None: ...
    def apagar_codigos_abertos(self, autorizador_id: int) -> None: ...
    def inserir_codigo(self, codigo: str, funcao: str, autorizador_id: int, criado_em: datetime, modo: str,
                       minutos: int) -> int: ...
    def por_codigo(self, codigo: str) -> Liberacao | None: ...
    def por_id(self, liberacao_id: int) -> Liberacao | None: ...
    def marcar_usado(self, liberacao_id: int, usuario_id: int, usado_em: datetime, ate: datetime | None) -> bool: ...
    def vigente(self, usuario_id: int, funcao: str, agora: datetime) -> Liberacao | None: ...
    def consumir(self, liberacao_ids: Iterable[int], agora: datetime) -> None: ...
    def revogar(self, liberacao_id: int, agora: datetime, encerrada_por: int) -> None: ...
    def ativas(self, agora: datetime, autorizador_id: int | None) -> list[Liberacao]: ...
    def recentes(self, autorizador_id: int | None, limite: int) -> list[Liberacao]: ...
