"""O que o ponto precisa do banco (a implementação fica na infraestrutura)."""

from datetime import datetime
from typing import Protocol

from ..horario import Horario
from .entidades import Funcionario, RegistroDePonto


class RepositorioDePonto(Protocol):
    """Sempre restrito a uma loja."""

    @property
    def empresa_id(self) -> int: ...

    def config(self, chave: str) -> str | None: ...
    def gravar_config(self, chave: str, valor: str) -> None: ...
    def trocar_geracao(self, de: int, para: int) -> bool: ...

    def funcionario(self, usuario_id: int) -> Funcionario | None: ...
    def funcionarios_com_ponto_aberto(self) -> list[Funcionario]: ...
    def gravar_horario(self, usuario_id: int, horario: Horario, exige_ponto: bool) -> None: ...
    def encerrar_sessoes(self, usuario_id: int) -> None: ...

    def aberto(self, usuario_id: int) -> RegistroDePonto | None: ...
    def abrir(self, funcionario: Funcionario, entrada: datetime, ip: str) -> bool: ...
    def fechar(self, usuario_id: int, saida: datetime, motivo: str, encerrado_por: int | None) -> int: ...
    def registros(self, de: datetime, ate: datetime, usuario_id: int | None) -> list[RegistroDePonto]: ...
