"""O que as contas precisam do banco e do guardador de senhas (as implementações ficam na infraestrutura)."""

from typing import Protocol

from .entidades import Conta


class Senhas(Protocol):
    """Hash de senha (lento e com sal): o domínio nunca vê nem guarda a senha."""

    def gerar(self, senha: str) -> str: ...
    def confere(self, senha_hash: str, senha: str) -> bool: ...


class RepositorioDeContas(Protocol):
    def conta(self, usuario_id: int) -> Conta | None: ...
    def contas_com_nome(self, nome: str, loja: str | None) -> list[Conta]: ...
    def existe_alguem(self) -> bool: ...
    def empresa_existe(self, empresa_id: int) -> bool: ...
    def nome_em_uso(self, empresa_id: int, nome: str) -> bool: ...

    def inserir(self, empresa_id: int, nome: str, senha_hash: str, papel: str, plataforma: bool, token: str) -> int: ...
    def gravar_senha(self, usuario_id: int, senha_hash: str, token: str) -> None: ...
    def gravar_totp_pendente(self, usuario_id: int, segredo: str) -> None: ...
    def ativar_totp(self, usuario_id: int, segredo: str, contador: int, token: str) -> None: ...
    def desativar_totp(self, usuario_id: int, token: str) -> None: ...
    def gravar_totp_ultimo(self, usuario_id: int, contador: int) -> None: ...
    def mudar_papel(self, usuario_id: int, papel: str) -> None: ...   # "fecha contas" só fica com garçom
    def definir_fecha_conta(self, usuario_id: int, pode: bool) -> None: ...
    def excluir(self, usuario_id: int) -> None: ...
